name: my-deploy
on:
  push:
    branches:
      - main
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Building Docker image
        run: docker build . -t ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u sergeev-s --password-stdin

      - name: Push image to ghcr
        run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Deploy to YandexCloud vm
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u sergeev-s -p "${{ secrets.GITHUB_TOKEN }}"
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }} || true
            docker stop deploy-test-nginx || true
            docker rm deploy-test-nginx || true
            docker network create deploy-test-net || true
            docker run -d --name deploy-test-nginx -p 8080:8080 --network deploy-test-net ghcr.io/${{ github.repository }}:${{ github.ref_name }} 

      - name: All done
        run: echo "All done in ${{ github.repository }}"
